api_platform:
    title: API SHOP GALLERY
    version: 1.0.0
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
    swagger:
         api_keys:
             JWT:
                name: Authorization
                type: header
    use_symfony_listeners: true
    defaults:
      extra_properties:
          standard_put: true
    keep_legacy_inflector: false
