App\Entity\Cart:
  operations:
    ApiPlatform\Metadata\GetCollection:
      method: GET
      formats:
        json: ['application/json']
    ApiPlatform\Metadata\Get:
      method: GET
      formats:
        json: ['application/json']
    ApiPlatform\Metadata\Post:
      method: POST
      formats:
        json: ['application/json']
    ApiPlatform\Metadata\Put:
      method: PUT
      formats:
        json: ['application/json']