security:
    password_hashers:
        App\Entity\User:
            algorithm: auto
            cost: 4 
            time_cost: 3 
            memory_cost: 10 
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
        dev_user_provider:
            id: app.user_provider.dev
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: true
        main:
            entry_point: 'security.authenticator.jwt.main'
            stateless: true
            lazy: true
            provider: dev_user_provider
            json_login:
                check_path: /auth # The name in routes.yaml is enough for mapping
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            jwt: ~
            refresh_jwt:
                check_path: /token/refresh 
                provider: dev_user_provider
